// <auto-generated />
namespace YinYang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TechImageAndData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TechImageAndData));
        
        string IMigrationMetadata.Id
        {
            get { return "201704121507500_TechImageAndData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
